apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: samplepythonapp
  name: samplepythonapp
spec:
  #replicas: 1
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: samplepythonapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: samplepythonapp
    spec:
      containers:
      - image: {{ .Values.image }}
        name: samplepythonapp
        resources: {}
status: {}