apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: samplepythonapp
  name: samplepythonapp 
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: samplepythonapp
status:
  loadBalancer: {}