apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: samplepythonapp
  name: samplepythonapp 
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 31500
    protocol: TCP
    targetPort: 5000
  selector:
    app: samplepythonapp
status:
  loadBalancer: {}