apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: simplejavaapp
  name: simplejavaapp
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: simplejavaapp
status:
  loadBalancer: {}